#!/bin/bash

sudo apt-get update

echo "Fixing Ubuntu 22.04.1 broken installer..."
sudo ubuntu-drivers autoinstall
sudo apt-get install ubuntu-restricted-addons
sudo apt-get upgrade -y gnome-remote-desktop

sudo apt-get upgrade -y

# again not sure
sudo apt-get dist-upgrade -y

# docker
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
curl -fsSL https://get.docker.com -o get-docker.sh
sudo get-docker.sh
sudo docker run hello-world
