#!/bin/bash

set -o errexit
set -o nounset
set -x

# install sudo if script ran in docker
if [ $UID = 0 ] ; then
  apt-get update
  apt-get install sudo
fi

sudo apt-get update

echo "Fixing Ubuntu 22.04.1 broken installer..."
type -p ubuntu-drivers >/dev/null && sudo ubuntu-drivers autoinstall
sudo apt-get install -y ubuntu-restricted-addons
sudo apt-get upgrade -y gnome-remote-desktop

# Upgrade
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove -y

# Basic utilities
sudo apt-get install -y \
  ack \
  curl \
  git \
  htop \
  jq \
  net-tools \
  nmap \
  tmux \
  vim
  
# OpenSSH
sudo apt-get install -y openssh-server

# NodeJS
curl -s https://deb.nodesource.com/setup_16.x | sudo bash
sudo apt-get install -y nodejs

# Yarn
sudo npm install -g yarn

# Zsh
sudo apt-get install -y zsh
chsh -s $(which zsh)


# GitHub CLI
# https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
type -p gh >/dev/null || curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
  && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
  && sudo apt update \
  && sudo apt install gh -y
if [ ! -f /.dockerenv ]; then
  gh auth login --web --git-protocol ssh
fi

# ~/code
mkdir -p ~/code
pushd ~/code

# ~/code/dotfiles
if [ -f /.dockerenv ]; then
  git clone https://github.com/stoooops/dotfiles.git
else
  git clone --recursive git@github.com:stoooops/dotfiles.git
fi
pushd dotfiles
yarn install
yarn setup

popd
popd

# configure local settings
echo "[user]
    email = corygabrielsen@gmail.com
" > ~/.gitconfig.local
 
# docker
# https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
if [ -f /.dockerenv ]; then
    echo "Running inside docker. Skipping docker-in-docker install."
else
    echo "Installing docker..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo bash get-docker.sh
    sudo docker run hello-world

    # Setup docker in rootless mode
    # 1. Install system requirements
    sudo sh -eux <<EOF
# Install newuidmap & newgidmap binaries
apt-get install -y uidmap
EOF
    # 2. setting up the Docker daemon in rootless mode for your user
    dockerd-rootless-setuptool.sh install
    docker run hello-world
fi
