#!/bin/bash

COLOR_NONE='\033[00m'
COLOR_BLACK="\033[30m"
COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"
COLOR_YELLOW="\033[33m"
COLOR_BLUE="\033[34m"
COLOR_MAGENTA="\033[35m"
COLOR_CYAN="\033[36m"


hookname=`basename $0`

FILE=`mktemp`
trap 'rm -f $FILE' EXIT
cat - > $FILE

for hook in $GIT_DIR/hooks/$hookname.*
do
  if test -x "$hook"; then
    echo -e "Running "$COLOR_BLUE"$hook"$COLOR_NONE"..."
    cat $FILE | $hook "$@"
    status=$?

    if test $status -ne 0; then
      echo -e $COLOR_RED"Hook $hook failed with error code "$status$COLOR_NONE
      exit $status
    fi
  fi
done

echo -e $COLOR_GREEN$hookname" completed successfully."$COLOR_NONE
