#!/usr/bin/env zsh
#
# The ~/.zshenv file is a configuration file for the Z shell (zsh) that is
# sourced (executed) for all invocations of the shell. It is used to define
# settings, aliases, functions, and keybindings that should be set for all
# invocations of the shell, including login shells, non-login shells, and
# interactive shells.
#
# This file should not contain commands, options, or keybindings that produce
# output or modify the shell. It is intended to be used to set environment
# variables, aliases, functions, and commands that should be run for all
# invocations of the shell. Options and keybindings should be set in the
# appropriate configuration file for the type of shell being run (e.g.,
# ~/.zshrc for interactive shells).
#
# To use the ~/.zshenv file, you can create a symlink to the file in your
# home directory using the ln command:
#
#   ln -s path/to/dotfiles/zsh/zshenv ~/.zshenv
#

#
# After much debugging, I haven't found a need for this. I'm leaving it here.
#
# Hours wasted: 2
#
. "$HOME/.cargo/env"

export PATH="$PATH:/home/dev/.foundry/bin"
